Chepelev lesson5
Chepelash/home-work pull request #4
Opened 2021-11-16 13:34 UTC by Chepelash

2021-11-16 17:35 UTC, Upforup requested changes

2021-11-16 17:35 UTC, Upforup commented on src/test/java/com/sbrf/reboot/atm/cassettes/CassetteTest.java
> +        Cassette<OneHundred> cassette = new Cassette<>(new ArrayList<OneHundred>() {{
Можно задать параметр типа ArrayList по общему интерфейсу: Banknote, тогда скомпилируется с несколькими элементами.

2021-11-16 20:39 UTC, Chepelash commented on src/test/java/com/sbrf/reboot/atm/cassettes/CassetteTest.java
> +        Cassette<OneHundred> cassette = new Cassette<>(new ArrayList<OneHundred>() {{
Исправлено

2021-11-17 08:48 UTC, Upforup approved these changes
ОК

2021-11-17 10:33 UTC, merged